GET http://localhost:8000/static/htmx.js
###
GET http://localhost:8000/static/style.css
###
GET http://localhost:8000/ldap?email=hoc
###
POST http://localhost:8000/newscanfile
Content-Type: application/json

{
    "file": "2025-12-09_19:01:00.log"
}

###
GET http://localhost:8000/unterlagen
###
GET http://localhost:8000/
###
GET http://localhost:8000/
###
GET http://localhost:8000/