const config = {
  ABGABEN_DIR: `${Deno.env.get("HOME")}/abgaben`,
  UNTERLAGEN_DIR: `${Deno.env.get("HOME")}/unterlagen`,
  LISTEN_HOST: Deno.env.get("LISTEN_HOST"),
  LISTEN_PORT: Number(Deno.env.get("LISTEN_PORT")),
  page_title: `${Deno.env.get("LISTEN_HOST") || "localhost"}:${Deno.env.get("LISTEN_PORT")}`,
  MAX_UPLOAD_MB: Number(Deno.env.get("MAX_UPLOAD_MB") || "50"),
  SERVICE_DN: Deno.env.get("SERVICE_DN")!,
  SERVICE_PW: Deno.env.get("SERVICE_PW")!,
  SERVICE_URL: Deno.env.get("SERVICE_URL")!,
  SEARCH_BASE: Deno.env.get("SEARCH_BASE")!,
  logdir: Deno.env.get("LOGDIR") || "/var/log/exampy",
  ldap_retry_wait_seconds: 7,
  spg_times: [
    "08:00",
    "08:50",
    "09:40",
    "09:55",
    "10:45",
    "11:35",
    "12:25",
    "12:35",
    "13:25",
    "14:15",
    "14:25",
    "15:15",
    "16:05",
    "16:15",
    "17:05",
    "17:10",
    "17:55",
    "18:40",
    "18:50",
    "19:35",
    "20:20",
    "20:30",
    "21:15",
    "22:00",
  ],
};
export default config;

for (const [key, value] of Object.entries(config)) {
  console.log(`config: ${key}: ${value}`);
}
